import { serve } from "https://deno.land/std@0.190.0/http/server.ts";
import { createClient } from "https://esm.sh/@supabase/supabase-js@2.39.3";

const corsHeaders = {
  'Access-Control-Allow-Origin': '*',
  'Access-Control-Allow-Headers': 'authorization, x-client-info, apikey, content-type',
};

interface MediaRequest {
  email_id: string;
  media_type: 'image' | 'banner' | 'video';
  prompt: string;
  user_id?: string;
}

serve(async (req) => {
  if (req.method === 'OPTIONS') {
    return new Response(null, { headers: corsHeaders });
  }

  try {
    const supabaseClient = createClient(
      Deno.env.get('SUPABASE_URL') ?? '',
      Deno.env.get('SUPABASE_SERVICE_ROLE_KEY') ?? ''
    );

    const { email_id, media_type, prompt, user_id }: MediaRequest = await req.json();

    console.log(`Generating ${media_type} for email ${email_id}`);

    // Verify email exists and get its details
    const { data: emailRecord, error: emailError } = await supabaseClient
      .from('Emails')
      .select('id, subject, user_id')
      .eq('id', email_id)
      .single();

    if (emailError || !emailRecord) {
      throw new Error('Email not found');
    }

    // Generate media using Lovable AI
    const enhancedPrompt = `Create a professional ${media_type} for email campaign: "${emailRecord.subject}". ${prompt}. Style: modern, professional, Czech business context.`;

    const aiResponse = await fetch('https://ai.gateway.lovable.dev/v1/chat/completions', {
      method: 'POST',
      headers: {
        'Authorization': `Bearer ${Deno.env.get('LOVABLE_API_KEY')}`,
        'Content-Type': 'application/json',
      },
      body: JSON.stringify({
        model: 'google/gemini-2.5-flash-image-preview',
        messages: [
          {
            role: 'user',
            content: enhancedPrompt
          }
        ],
        modalities: ['image', 'text']
      }),
    });

    if (!aiResponse.ok) {
      throw new Error(`AI Gateway error: ${aiResponse.status}`);
    }

    const aiData = await aiResponse.json();
    
    // Extract image from AI response
    let mediaUrl = '';
    let fileName = '';
    
    if (aiData.choices?.[0]?.message?.images?.[0]?.image_url?.url) {
      const base64Data = aiData.choices[0].message.images[0].image_url.url;
      
      // Generate filename
      fileName = `${media_type}-${email_id}-${Date.now()}.png`;
      
      // Convert base64 to blob
      const base64Response = await fetch(base64Data);
      const blob = await base64Response.blob();
      
      // Upload to Supabase Storage
      const { data: uploadData, error: uploadError } = await supabaseClient.storage
        .from('email-media')
        .upload(fileName, blob, {
          contentType: 'image/png',
          upsert: false
        });

      if (uploadError) {
        console.error('Storage upload error:', uploadError);
        throw new Error(`Failed to upload ${media_type}: ${uploadError.message}`);
      }

      // Get public URL
      const { data: urlData } = supabaseClient.storage
        .from('email-media')
        .getPublicUrl(fileName);
      
      mediaUrl = urlData.publicUrl;
    } else {
      throw new Error('No media generated by AI');
    }

    // Save media record to EmailMedia table
    const { data: mediaRecord, error: mediaError } = await supabaseClient
      .from('EmailMedia')
      .insert({
        email_id,
        media_type,
        media_url: mediaUrl,
        file_name: fileName,
        generation_prompt: prompt,
        generated_by_ai: true,
        file_size: null // Will be updated if needed
      })
      .select()
      .single();

    if (mediaError) {
      console.error('Error saving media record:', mediaError);
      throw new Error(`Failed to save media record: ${mediaError.message}`);
    }

    console.log(`${media_type} generated and saved: ${fileName}`);

    return new Response(
      JSON.stringify({
        success: true,
        media_id: mediaRecord.id,
        media_url: mediaUrl,
        file_name: fileName,
        media_type,
        message: `${media_type} generated successfully`
      }),
      {
        headers: { ...corsHeaders, 'Content-Type': 'application/json' },
        status: 200,
      }
    );

  } catch (error: any) {
    console.error('Generate Media error:', error);
    
    return new Response(
      JSON.stringify({
        success: false,
        error: error?.message || 'Unknown error occurred'
      }),
      {
        headers: { ...corsHeaders, 'Content-Type': 'application/json' },
        status: 500,
      }
    );
  }
});