// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rrmvxsldrjgbdxluklka.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJybXZ4c2xkcmpnYmR4bHVrbGthIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM2MDk5NzMsImV4cCI6MjA2OTE4NTk3M30.fYPxCqMsyWfePJuBEiC8e8_vaHwJIJVmD3S3PrMF7fU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});